### PR TITLE
CakePHP 3 version

### PR DESCRIPTION
**Pull request by hoomanna**
Hi,

We just port a version of Cake-Resque for Cakephp3.. It's PSR-4 compatible.. 
Your comments are welcome..

Regards,
Hooman Naghiee

### CODE REVIEW

**Comment by amiri27** [comment]
Hi @kamisama, could you please help us to fix the build problems? As I see we are in need to create another branch from CakePHP3 plugin and work on that faster..

Regards,

**Comment by kamisama** [comment]
Did all tests pass locally on your side ? Is the issue only with the travis config ?

**Comment by kamisama** [comment]
Seems that every tests are failing, for 2 reasons:
- They were not refactored for Cake3 yet
- phpunit 4 removed some mocking functions

Is that PR a draft for Cake3, and you're expecting a merge, then working on the master, or is it supposed to be a working plugin ?

**Comment by RTLer** [comment]
Hi Kamisama,

Thanks for the marge you made yesterday on php-resque-ex repository.. 
So for this branch as we started working on that none of tests didn't work. We made the changes and this is a working prototype.. All of functions are working and there's a need to just update the tests to latest version of phpunit.
I think that if you merge these changes we can work faster in order to fix the tests and get them to work. I'm ready to that and we need your help also..

Regards,

**Comment by wa0x6e** [comment]
Merged, and I updated travis. 
Next step is fixing the code standard and phpunit tests.

**Comment by amiri27** [comment]
@kamisama could please help us to fix the phpunit tests? If you run one of tests we can do and fix the others..

Regards,

**Comment by wa0x6e** [comment]
I've created another branch (fix/tests) for the tests

**Comment by wa0x6e** [comment]
See #90

**Comment by shivdhwaj** [comment]
@birdy247 : Did you achieved this?

**Pull request merged**
